# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec para FerramentasAcademicas.exe

a = Analysis(
    ['iniciar.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static',       'static'),
        ('modules',      'modules'),
        ('app.py',         '.'),
        ('analisador.py',  '.'),
        ('verificador.py', '.'),
        ('config.py',      '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.base',
        'starlette.responses',
        'starlette.requests',
        'starlette.datastructures',
        'anyio',
        'anyio._backends._asyncio',
        'anyio._backends._trio',
        'anthropic',
        'httpx',
        'httpcore',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.hooks',
        'requests.models',
        'requests.sessions',
        'requests.structures',
        'requests.utils',
        'requests.compat',
        'requests.packages',
        'urllib3',
        'urllib3.util',
        'urllib3.util.retry',
        'urllib3.util.ssl_',
        'urllib3.contrib',
        'urllib3.contrib.pyopenssl',
        'certifi',
        'charset_normalizer',
        'idna',
        'docx',
        'lxml',
        'lxml.etree',
        'fitz',
        'multipart',
        'dotenv',
        'email.mime',
        'email.mime.multipart',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'pandas', 'scipy'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FerramentasAcademicas',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
